---
- name: Cleanup db Configuration
  hosts: appdb
  roles:
  - cleanup-db

- name: Cleanup App Configuration
  hosts: apps
  roles:
  - cleanup-app

- name: Cleanup Web Configuration
  hosts: frontend
  roles:
  - cleanup-web
