---
- name: Cleanup db Configuration
  hosts: db
  roles:
  - cleanup-db

- name: Cleanup App Configuration
  hosts: apps
  roles:
  - cleanup-app

- name: Cleanup Web Configuration
  hosts: frontends
  roles:
  - cleanup-web
