---
- name: Smoke Test
  hosts: localhost
  tasks:
  - name: test if app is reachable
    uri: 
      url: "http://192.168.56.103"
      return_content: yes
    register:  smoke
    tags:
      - smoke

  - name: Show Web Page
    debug: msg="{{ smoke }}"

  - name: check the smoke return page content
    assert:
     that: "'Ansible has done its job - Welcome to Tomcat' in smoke.content" 
    tags:
      - smoke

